#!/bin/bash

cd /opt/orange/usergrid_python/

PWD=`pwd`
echo current working dir is ${PWD}
#/usr/bin/python3 /opt/orange/usergrid_python/setup.py install
#/usr/bin/python /opt/orange/usergrid_python/setup.py install

exit
